/* eslint-disable*/
// Entity esp_ButtonAdvancedSetting
export const esp_buttonadvancedsettingMetadata = {
  typeName: "mscrm.esp_buttonadvancedsetting",
  logicalName: "esp_buttonadvancedsetting",
  collectionName: "esp_buttonadvancedsettings",
  primaryIdAttribute: "esp_buttonadvancedsettingid",
  attributeTypes: {
    // Numeric Types
    importsequencenumber: "Integer",
    timezoneruleversionnumber: "Integer",
    utcconversiontimezonecode: "Integer",
    versionnumber: "BigInt",
    // Optionsets
    esp_executionmode: "Optionset",
    esp_syncconfirmationboxredirectmode: "Optionset",
    statecode: "Optionset",
    statuscode: "Optionset",
    // Date Formats
    createdon: "DateAndTime:UserLocal",
    modifiedon: "DateAndTime:UserLocal",
    overriddencreatedon: "DateOnly:UserLocal",
  },
  navigation: {
    createdby: ["mscrm.systemuser"],
    createdonbehalfby: ["mscrm.systemuser"],
    esp_MainButtonSetting: ["mscrm.esp_buttonsettings"],
    esp_SettingLanguage: ["mscrm.esp_language"],
    modifiedby: ["mscrm.systemuser"],
    modifiedonbehalfby: ["mscrm.systemuser"],
    ownerid: ["mscrm.principal"],
    owningbusinessunit: ["mscrm.businessunit"],
    owningteam: ["mscrm.team"],
    owninguser: ["mscrm.systemuser"],
  },
};

// Attribute constants
export const enum esp_ButtonAdvancedSettingAttributes {
  CreatedBy = "createdby",
  CreatedByName = "createdbyname",
  CreatedByYomiName = "createdbyyominame",
  CreatedOn = "createdon",
  CreatedOnBehalfBy = "createdonbehalfby",
  CreatedOnBehalfByName = "createdonbehalfbyname",
  CreatedOnBehalfByYomiName = "createdonbehalfbyyominame",
  esp_AsyncFormNotification = "esp_asyncformnotification",
  esp_AsyncFormNotificationText = "esp_asyncformnotificationtext",
  esp_ButtonAdvancedSettingId = "esp_buttonadvancedsettingid",
  esp_ConfirmationDialogCancelLabel = "esp_confirmationdialogcancellabel",
  esp_ConfirmationDialogConfirmLabel = "esp_confirmationdialogconfirmlabel",
  esp_ConfirmationDialogSubtitle = "esp_confirmationdialogsubtitle",
  esp_ConfirmationDialogText = "esp_confirmationdialogtext",
  esp_ConfirmationDialogTitle = "esp_confirmationdialogtitle",
  esp_ExecutionMode = "esp_executionmode",
  esp_MainButtonSetting = "esp_mainbuttonsetting",
  esp_MainButtonSettingName = "esp_mainbuttonsettingname",
  esp_SettingID = "esp_settingid",
  esp_SettingLanguage = "esp_settinglanguage",
  esp_SettingLanguageName = "esp_settinglanguagename",
  esp_ShowConfirmationDialog = "esp_showconfirmationdialog",
  esp_SyncConfirmationBox = "esp_syncconfirmationbox",
  esp_SyncConfirmationBoxConfirmLabel = "esp_syncconfirmationboxconfirmlabel",
  esp_SyncConfirmationBoxRedirect = "esp_syncconfirmationboxredirect",
  esp_SyncConfirmationBoxRedirectCancelLabel = "esp_syncconfirmationboxredirectcancellabel",
  esp_SyncConfirmationBoxRedirectConfirmLabel = "esp_syncconfirmationboxredirectconfirmlabel",
  esp_SyncConfirmationBoxRedirectMode = "esp_syncconfirmationboxredirectmode",
  esp_SyncConfirmationBoxRedirectSubtitle = "esp_syncconfirmationboxredirectsubtitle",
  esp_SyncConfirmationBoxRedirectText = "esp_syncconfirmationboxredirecttext",
  esp_SyncConfirmationBoxRedirectTitle = "esp_syncconfirmationboxredirecttitle",
  esp_SyncConfirmationBoxText = "esp_syncconfirmationboxtext",
  esp_SyncConfirmationBoxTitle = "esp_syncconfirmationboxtitle",
  esp_SyncFormNotification = "esp_syncformnotification",
  esp_SyncFormNotificationText = "esp_syncformnotificationtext",
  esp_SyncRefreshForm = "esp_syncrefreshform",
  esp_SyncSpinner = "esp_syncspinner",
  esp_SyncSpinnerText = "esp_syncspinnertext",
  esp_SyncSuccessFormNotification = "esp_syncsuccessformnotification",
  esp_SyncSuccessFormNotificationText = "esp_syncsuccessformnotificationtext",
  ImportSequenceNumber = "importsequencenumber",
  ModifiedBy = "modifiedby",
  ModifiedByName = "modifiedbyname",
  ModifiedByYomiName = "modifiedbyyominame",
  ModifiedOn = "modifiedon",
  ModifiedOnBehalfBy = "modifiedonbehalfby",
  ModifiedOnBehalfByName = "modifiedonbehalfbyname",
  ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame",
  OverriddenCreatedOn = "overriddencreatedon",
  OwnerId = "ownerid",
  OwnerIdName = "owneridname",
  OwnerIdType = "owneridtype",
  OwnerIdYomiName = "owneridyominame",
  OwningBusinessUnit = "owningbusinessunit",
  OwningBusinessUnitName = "owningbusinessunitname",
  OwningTeam = "owningteam",
  OwningUser = "owninguser",
  statecode = "statecode",
  statuscode = "statuscode",
  TimeZoneRuleVersionNumber = "timezoneruleversionnumber",
  UTCConversionTimeZoneCode = "utcconversiontimezonecode",
  VersionNumber = "versionnumber",
}
